export const CREATE_REEL_ACTION_REQUEST = "CREATE_REEL_ACTION_REQUEST";
export const CREATE_REEL_ACTION_SUCCESS = "CREATE_REEL_ACTION_SUCCESS";
export const CREATE_REEL_ACTION_FAILURE = "CREATE_REEL_ACTION_FAILURE";

export const FETCH_USER_REEL_ACTION_REQUEST = "FETCH_USER_REEL_ACTION_REQUEST";
export const FETCH_USER_REEL_ACTION_SUCCESS = "FETCH_USER_REEL_ACTION_SUCCESS";
export const FETCH_USER_REEL_ACTION_FAILURE = "FETCH_USER_REEL_ACTION_FAILURE";

export const ALL_REEL_ACTION_REQUEST = "ALL_REEL_ACTION_REQUEST";
export const ALL_REEL_ACTION_SUCCESS = "ALL_REEL_ACTION_SUCCESS";
export const ALL_REEL_ACTION_FAILURE = "ALL_REEL_ACTION_FAILURE";

export const DELETE_REEL_ACTION_REQUEST = "DELETE_REEL_ACTION_REQUEST";
export const DELETE_REEL_ACTION_SUCCESS = "DELETE_REEL_ACTION_SUCCESS";
export const DELETE_REEL_ACTION_FAILURE = "DELETE_REEL_ACTION_FAILURE";
