export const CREATE_POST_REQUEST = "CREATE_POST_REQUEST";
export const CREATE_POST_SUCCESS = "CREATE_POST_SUCCESS";
export const CREATE_POST_FAILURE = "CREATE_POST_FAILURE";

export const UPDATE_POST_REQUEST = "UPDATE_POST_REQUEST";
export const UPDATE_POST_SUCCESS = "UPDATE_POST_SUCCESS";
export const UPDATE_POST_FAILURE = "UPDATE_POST_FAILURE";

export const DELETE_POST_REQUEST = "DELETE_POST_REQUEST";
export const DELETE_POST_SUCCESS = "DELETE_POST_SUCCESS";
export const DELETE_POST_FAILURE = "DELETE_POST_FAILURE";

export const GET_ALL_POST_REQUEST = "GET_ALL_POST_REQUEST";
export const GET_ALL_POST_SUCCESS = "GET_ALL_POST_SUCCESS";
export const GET_ALL_POST_FAILURE = "GET_ALL_POST_FAILURE";

export const POST_DEATIL_BY_ID_REQUEST = "POST_DETAILS_BY_ID_REQUEST";
export const POST_DEATIL_BY_ID_SUCCESS = "POST_DETAILS_BY_ID_SUCCESS";
export const POST_DEATIL_BY_ID_FAILURE = "POST_DETAILS_BY_ID_FAILURE";

export const GET_USER_SAVED_POST_REQUEST = "GET_USER_SAVED_POST_REQUEST";
export const GET_USER_SAVED_POST_SUCCESS = "GET_USER_SAVED_POST_SUCCESS";
export const GET_USER_SAVED_POST_FAILURE = "GET_USER_SAVED_POST_FAILURE";

export const LIKE_POST_REQUEST = "LIKE_POST_REQUEST";
export const LIKE_POST_SUCCESS = "LIKE_POST_SUCCESS";
export const LIKE_POST_FAILURE = "LIKE_POST_FAILURE";

export const SAVED_POST_REQUEST = "SAVED_POST_REQUEST";
export const SAVED_POST_SUCCESS = "SAVED_POST_SUCCESS";
export const SAVED_POST_FAILURE = "SAVED_POST_FAILURE";

export const GET_USER_POST_REQUEST = "GET_USER_POST_REQUEST";
export const GET_USER_POST_SUCCESS = "GET_USER_POST_SUCCESS";
export const GET_USER_POST_FAILURE = "GET_USER_POST_FAILURE";

export const CREATE_COMMENT_REQUEST = "CREATE_COMMENT_REQUEST";
export const CREATE_COMMENT_SUCCESS = "CREATE_COMMENT_SUCCESS";
export const CREATE_COMMENT_FAILURE = "CREATE_COMMENT_FAILURE";

export const COMMENT_LIKE_REQUEST = "COMMENT_LIKE_REQUEST";
export const COMMENT_LIKE_SUCCESS = "COMMENT_LIKE_SUCCESS";
export const COMMENT_LIKE_FAILURE = "COMMENT_LIKE_FAILURE";

export const GET_ALL_COMMENT_OF_THE_POST_REQUEST =
  "GET_ALL_COMMENT_OF_THE_POST_REQUEST";
export const GET_ALL_COMMENT_OF_THE_POST_SUCCESS =
  "GET_ALL_COMMENT_OF_THE_POST_SUCCESS";
export const GET_ALL_COMMENT_OF_THE_POST_FAILURE =
  "GET_ALL_COMMENT_OF_THE_POST_FAILURE";
